sudo: false
language: node_js
node_js:
  - 'node'
addons:
  apt:
    packages:
      - xvfb
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - npm install
before_script:
  - export DISPLAY=':99.0'
  - "sh -e /etc/init.d/xvfb start" #dont run xvfb directly, as it does not handle multiple concurrent instances that way
  - sleep 3 # give xvfb some time to start
script: npm run test:ci
